### ISSUE TITLE
hdecode.o multiple definition of hp make error

### ISSUE THREAD

**Issue by filip-minic** [Dridi/cashpack#7]
Dear developers,

there seems to be an issue building this on Ubuntu 20.10 when trying to make the latest master release or latest release.

The error I seem to be encountering is:
```
/usr/bin/ld: hdecode.o:/home/fminic/cashpack-0.3/tst/hdecode.c:129: multiple definition of `hp'; tst.o:/home/fminic/cashpack-0.3/tst/tst.c:47: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:716: hdecode] Error 1
make: *** [Makefile:494: all-recursive] Error 1
```

Any idea what can be causing this?

Thanks in advance!

**Comment by Dridi** [comment]
This is already fixed by e54b60465ef7fc5735fd040b23b55b3edea98975 but not yet in a release. I should probably cut one.

**Comment by filip-minic** [comment]
Hello Dridi,

in the meantime I have fixed it in the same way locally and managed to compile it. Would be great if you could create an "out of the box" working release.

Best Regards

**Comment by Dridi** [comment]
I have finally cut a release, sorry for taking so long.

https://github.com/Dridi/cashpack/releases/tag/v0.4

**Comment by Dridi** [comment]
You might as well skip 0.4: https://github.com/Dridi/cashpack/releases/tag/v0.5
